### ISSUE TITLE
Fails to run individual test in RubyMine 2019.3

### ISSUE THREAD

**Issue by fcatalano** [petekinnecom/test_launcher#4]
It appears that RubyMine 2019.3 passes the name parameter differently the before. In my output I'm seeing:
`--name /your_test_name/`
Previously it looked like:
`--name=your_test_name`

This causes test_launcher to try to cd into a directory named `your_test_name`, which does not exist, and fails.

It still works on the CLI, just not from within RubyMine.

**Comment by liyiran** [comment]
I have the same issue!

**Comment by petekinnecom** [comment]
Thanks for the report/fix! Fixed here: https://github.com/petekinnecom/test_launcher/commit/9da3658a5cacd4ef51dcb7fb4bdb301515f993dc with version 2.23.0
